apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Any changes run : oc apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic

  # Global settings
  global:
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 8.2.3
    #externalIP: 10.0.2.15
    #externalDbIP: 10.0.2.15
    #externalTimescaleDBIP: 10.0.2.15
    externalArangoDBName: arango.turbo.svc.cluster.local
    #enableExternalSecrets: true
    storageClassName: ibmc-vpc-block-10iops-mzr

