
---
# Source: service-account/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: turbonomic
  name: turbonomic
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  labels:
    helm.sh/chart: service-account-0.6.0
    app.kubernetes.io/name: turbonomic
    app.kubernetes.io/instance: service-account
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: service-account/templates/scc-anyuid.yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-3"
    argocd.argoproj.io/sync-options: Validate=false
    kubernetes.io/description: anyuid provides all features of the restricted SCC
      but allows users to run with any UID and any GID.
  name: turbonomic-turbonomic-anyuid
  labels:
    helm.sh/chart: service-account-0.6.0
    app.kubernetes.io/name: turbonomic
    app.kubernetes.io/instance: service-account
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:turbonomic:turbonomic
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
